repos:
-   repo: local
    hooks:
    -   id: make-test
        name: make-test
        entry: "/opt/homebrew/opt/make/libexec/gnubin/make test"
        language: script
        pass_filenames: false
        always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ".benchmarks"
    -   id: trailing-whitespace
    -   id: check-case-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--max-line-length", "120"]
